### ISSUE TITLE
Possible Feature?

### ISSUE THREAD

**Issue by rabfulton** [camrein/EzGraver#14]
Firstly, thank you very much for creating this software.

I was thinking it might be possible to do greyscale images by taking an image and splitting it into say 4 levels of grey. The 4 seperated images could then be burned in sequence at different power levels corresponding to the greyscales.

**Comment by camrein** [comment]
Sorry for the late reply. Glad you like it.

I really like your idea about adding different shades this way. So, thanks a lot for coming up with it. Currently I'm busy with extending the reporting of the actual progress (progress bar in other words), but haven't gotten time to complete it the past days.
As I will have to study for exams the next month, I can't like really tell you when I get the chance to imlement it.
But may I ask which OS you are using? If it's not such a time consuming task I may add the feature in a seperate branch so you can check it out and compile it yourself.

**Comment by rabfulton** [comment]
I run on Arch Linux. No rush for you to implement this, you are doing it for free after all. It should already be possible to do this manually using a capable image editor and running the software in an iterative fashion.

With all the talk of trojans in the software supplied with the neje I am somewhat suprised you software is not getting more attention.

**Comment by camrein** [comment]
Soo I gave it a first shot. It is far from complete, but you might be interested in its current state. You can grab it from the "grayscale" branch [here](https://github.com/camrein/EzGraver/tree/grayscale).

In the current state, EzGraver does not automatically upload each layer (that's how I've called the different levels of gray in a grayscale image as I think it suits pretty well the goal of this functionality). You can see an overview of the transformation with layer "0". The higher values will display only the parts being part of the selected layer.
Due to the lack of automation, you have (for now) to manually cycle through the different layers. Furthermore, for each layer the upload and start buttons have to be invoked manually (don't forget to adjust the burn time ;-)).

So currently, there's not much of benefit over manually splitting the image. Additionally, the number of layers is currently hard-coded to 8 (changing it is easy as I do the calculations anyway, so only an integration into the UI is necessary).

I'd be glad if you give it a short try and tell me if it is going the direction you've imagined.

**Comment by camrein** [comment]
As I was a little bit ambitious, I have extended the version in the branch, so now you're able to select the number of layers. :-)

Automatic engraving of all layers requires a little bit more effort. It needs setting the burn time for each layer manually and also keeping track of the current engraving process. But I think the current state is pretty neat.

**Comment by camrein** [comment]
After finally getting the time to do a few tests I released v2.1.0 which adds your requested feature.
It seems the "color" distribution is not always optimal. If there is any demand, I may improve this weakness.
