### ISSUE TITLE
Suggestion: add keyboard movements

### ISSUE THREAD

**Issue by GilDev** [camrein/EzGraver#27]
So now that it works on my Mac, I played with it and it's pretty great. The only thing missing to make it, for me, the killer app, is to be able to move the laser with keyboard arrows instead of clicking on “right”, “left”, “up” and “down”.
Also some buttons to rotate the image and flip it would be quite useful. =)

**Comment by camrein** [comment]
Thanks a lot for your suggestions. I've integrated both of them in the release [v3.1.0](https://github.com/camrein/EzGraver/releases/tag/v3.1.0).

Would you mind sharing your trouble of getting EzGraver to work on your Mac and how you solved it? I'm sure this would be helpful for other Mac users as well. =)

**Comment by GilDev** [comment]
Woaw so much reactive! =O Thanks a lot!
My Mac problems were discussed in an early issue (#21), sorry it was unclear.

I'm sorry about this but I have more suggestions to keep you busy if you ever want to implement some of them! =) I hope it can be useful:
* I'm still unsure about how the “Layered” mode works and why it is useful, maybe adding a short description in the README would help users.
* Add a progress bar for the engraving process, or even better, the image getting red as the laser engraves, like on the original NEJE's software. It shows precisely where the laser is and it has often been useful to engrave just a bit of the image to test different materials/burn times.
* I often go out of bound while positioning the laser before engraving. That means when I start engraving, the motors will eventually get stuck at the endpoint and the engraving will fail. Would be nice to be able to specify the engraving area's dimensions (I think all NEJEs are 38x38 mm for now but that could change in the future…) and having some kind of dotted rectangle the size of the image that moves in sync with the laser/bed when you position your image before engraving. Here's a representation of what I picture with a black positioning rectangle with solid border:
![Example of positioning rectangle](https://user-images.githubusercontent.com/3149748/30342096-ce6833ee-97f8-11e7-807b-ffdf4072ca9b.png)
* A ruler on all sides of the “canvas” (outside the image, on its sides).
* Automatically show the picture's dimensions in real life, it's even better than a ruler! Would calculate picture's size and show real life dimensions under the image. Here's what I picture (I have put the dimensions onto the image but they would be better elsewhere):
![ezgraverdimensions](https://user-images.githubusercontent.com/3149748/30342179-2e03c6ce-97f9-11e7-86c7-dce6a9fa1858.png)

**Comment by camrein** [comment]
I just happened to have some spare time and knew that your initial requests could be quickly implemented. =)
Ah great. However, I thought I have removed the faulty OSX builds from the releases page, so these are no longer downloaded. Just to be sure, you shouldn't have to install anything but EzGraver itself because all dependencies should be packaged within the *.dmg file. If that is not the case, the package was not built correctly. The only thing that might be necessary is the installation of a driver, but that shouldn't cause EzGraver fail to start. In this situation, EzGraver will simply be unable to detect the device.

Wow, that's quite a bunch. Just for the sake of tidiness, would you mind creating separate requests for these requests (you can combine related ones) so I can also reply to them individually? Then we can close your initial request. Nevertheless, I cannot guarantee that I get the time to implement the larger requests anytime soon.

**Comment by GilDev** [comment]
Alright, good to know!
Sure, I'll make separate ones. These are only suggestions of course, and I know if I really want them I should look into coding them myself but I don't know QT at all and don't have much time right now. =/

**Comment by GilDev** [comment]
Also, I can't try right now with my engraver, but windows items gets focused when I press arrow keys. It cycles between checkboxes, sliders and menus. Because of that, I'm not sure it would actually control the laser position with the keyboard.

**Comment by camrein** [comment]
Thanks a lot for your effort. To be honest, EzGraver was just an idea to refresh my C++ knowledge. I haven't used Qt before, but I thought I'll give it a try. =)

That's the same behavior on my windows machine so expect it to be alright. Furthermore, I think that visual feedback will help people to recognize this new feature.

About the layering feature:
You're most likely confused because it is not fully working as intended. On images with little colors and contrast, the automatic color selection is pretty weak, so there is no real benefit. But if you load a colorful image you'll eventually notice that using more layers will help to represent the original image better. However, with more layers, the issue with the color selection becomes more significant. The actual functionality is as follows: The special "layer" 0 represents the image how it has been split into different layers whereas each shade represents one layer. The layers 1 and upwards each represent one of these shades initially shown in the overview. By gradually changing the burn time for each layer you'll be able to engrave the image with different shades.
I have already tried to rework the color selection mechanism to a more sophisticated one. But as you probably expect, I had some issues and couldn't implement it as I desired, and thus I stalled this enhancement for now. Also, as the feature is not mature by now, I didn't want to write a description about it to avoid frustration. =)

**Comment by GilDev** [comment]
Alright, thanks a lot for your work, it allows me and plenty other I'm sure to use these nice little engravers on Mac and Linux with some quite nice new features! =)
The best way to have feedback, I think, would be to make the “left”, “right”, “down” and “up” buttons in the “pressed” state when you press a keyboard arrow. That would be a nice visual feedback and you wouldn't focus other items which is, after all, useless and confusing (you can think you are going to change the scale when you want to move the laser, and maybe it will indeed change the scale).

**Comment by camrein** [comment]
Oh, I misread your report about arrow keys. On my windows machine, the proper button gets highlighted when pressing one of the arrow keys. So yeah, that way you described it is rather confusing.
That's a rather unfortunate situation that the behavior differs between the operating systems. I'm just wondering, do you have the same behavior when an engraver is connected and is the head moving? For me, changing the focus between the widgets only happens when the movement buttons are disabled. This behavior is perfectly fine in my opinion. After all, the arrow keys would not have an effect when these buttons are disabled.

Last but not least, I do not really like interfering in the default behavior of the frameworks as it often gets hacky.

**Comment by camrein** [comment]
As I was testing EzGraver with Linux Mint, I tried the interaction with the keyboard shortcuts. The behavior is the same as on my windows machine. When not connected to an engraver (the buttons are disabled), the keyboard arrows are used to navigate through the different widgets (changing the focus).
As soon as EzGraver is connected to a device, the buttons are enabled and retrieve the arrow key actions and give visual feedback just as they were clicked with the mouse and no longer change the focus.
