### ISSUE TITLE
Need help downloading/building 

### ISSUE THREAD

**Issue by bolstav** [camrein/EzGraver#37]
Hi all. I really like the look of your software.  I just bought a 1000w neje laser engraver and would like to run your burning software so I can engrave.  I am on a MacBook pro running el captain and the software provided doesn't seem to work.  It finds and connects to the engraver but doesn't engrave. 

I'm realky not too tech savvy so would anyone be able to give me step by step instructions on how to add the drivers and where i can find them as well as simple instructions on how to build the software? 

I've never engraved before and really don't know how to get the machine working from my mac. Any help is really appreciated. 

Thanks heaps.

Bolsta

**Comment by lmftiv** [comment]
As far as I have understood an tested the current version of ezgraver doesn't yet fully work with the newest (v3) Neje engravers. The transferring of the bitmap is still work in progress. Please correct me if I'm wrong.

**Comment by camrein** [comment]
@lmftiv is right with the claim that the latest NEJE devices are not fully supported at this time, in particular, protocol v3.

Before installing anything, make sure you actually need the drivers. To do so, simply check if the device you're connecting to is NOT listed when the engraver is dis-connected and is listed when it's connected. If that is the case, you do not have to install anything further as your OS already has the necessary drivers. Otherwise, you most likely have to install the required drivers on your MacBook. I do not want to link possible sources directly, but I heard reports that googling for drivers CH340 CH341 leads to the desired results.
If you verified that the device listed in the selection dropdown is indeed your engraver, ensure you have selected the correct protocol. You can change it by clicking the dropdown containing the v1, v2, and v3 selections. Just try through the different versions by re-connecting the device and sending one of the commands that are verified to work (this should be anything but the upload button). For example, you should notice that the engraving head does move a bit when clicking the "Up" button.
If you identified protocol v3 to match your device, you're a bit of bad luck, as @lmftiv already mentioned, the upload functionality is not working at this time (see #34). If none of the three selections appears to be working, you've probably a device that has a protocol which is entirely not supported by now.

**Comment by bolstav** [comment]
Thanks very much guys. Really appreciate your help
